Add CRU_NAMESPACE_{BEGIN,END} annotations
calderpg/common_robotics_utilities pull request #70
Opened 2023-07-31 18:47 UTC by jwnimmer-tri

This allows downstream projects to vary the symbol names to avoid ODR compatibility headaches (https://github.com/RobotLocomotion/drake/issues/17231).

See https://github.com/RobotLocomotion/drake/pull/19893 for Drake CI testing.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/calderpg/common_robotics_utilities/70)

2023-08-01 00:08 UTC, jwnimmer-tri commented
+@calderpg for review, please.

2023-08-01 14:53 UTC, calderpg requested changes
Overall looks reasonable. I assume there's not an easy way to test that `CRU_NAMESPACE_{BEGIN,END}` are used appropriately from the cmake and that the Drake build of CRU will be the practical test of using this feature?

> Reviewed 41 of 41 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/calderpg/common_robotics_utilities/70#-:-NalXOAg5SXUNU2rXR62:bjc75fs)* status: 0 of 1 LGTMs obtained

___
*[`include/common_robotics_utilities/cru_namespace.hpp` line 3 at r1](https://reviewable.io/reviews/calderpg/common_robotics_utilities/70#-NalW2IfEyTRhyJ1mdR4:-NalW2IfEyTRhyJ1mdR5:b-f9bj0l) ([raw file](https://github.com/calderpg/common_robotics_utilities/blob/05240702f136feb9d5cd63e65b6753d8f9a04b92/include/common_robotics_utilities/cru_namespace.hpp#L3)):*
> ```cpp
> #pragma once
> 
> // Downstream projects can adjust these to tweak the project namespace.
> ```

I think this deserves an example or reference as to what configuration would be possible. As I understand it, really the only thing that could go here is an `inline namespace`, anything else would change the API and fail to compile.


<!-- Sent from Reviewable.io -->

2023-08-01 16:19 UTC, jwnimmer-tri reviewed
> I assume there's not an easy way to test that `CRU_NAMESPACE_{BEGIN,END}` are used appropriately from the cmake and that the Drake build of CRU will be the practical test of using this feature?

Mostly yes.

If you preferred, the default values here could be non-empty (e.g., BEGIN could default to`inline namespace v1 __attribute__ ((visibility ("hidden"))) {`) which would add symbol versioning to CRU in support of something like CRU stable releases.  That didn't seem particularly relevant, but it would ensure that when the CMake build happens it would detect any macro mis-matches immediately.  I am OK either way.

> *[Reviewable](https://reviewable.io/reviews/calderpg/common_robotics_utilities/70#-:-NalqVi2DG1liRFoJyiZ:bb9d55r)* status: 0 of 1 LGTMs obtained

___
*[`include/common_robotics_utilities/cru_namespace.hpp` line 3 at r1](https://reviewable.io/reviews/calderpg/common_robotics_utilities/70#-NalW2IfEyTRhyJ1mdR4:-NaltGSh7mSySJuXcSZu:b-896fix) ([raw file](https://github.com/calderpg/common_robotics_utilities/blob/05240702f136feb9d5cd63e65b6753d8f9a04b92/include/common_robotics_utilities/cru_namespace.hpp#L3)):*
<details><summary><i>Previously, calderpg (Calder Phillips-Grafflin) wrote…</i></summary><blockquote>

I think this deserves an example or reference as to what configuration would be possible. As I understand it, really the only thing that could go here is an `inline namespace`, anything else would change the API and fail to compile.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-01 16:19 UTC, jwnimmer-tri reviewed
Correction: any default would not use "hidden", just `inline namespace v1 {`.

> *[Reviewable](https://reviewable.io/reviews/calderpg/common_robotics_utilities/70#-:-NaltPD0EzxK9q7CFj_z:bdr02p9)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2023-08-02 02:16 UTC, calderpg requested changes
Please go ahead with an `inline namespace v1 {` form, I'd like to have the CMake build catch mis-matches.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/calderpg/common_robotics_utilities/70#-:-Nao00G52zFEd_8mq1Ya:b-4oq9yp)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2023-08-02 20:44 UTC, jwnimmer-tri commented
This should be good to go now.  The Anzu CI test on PR 10758 passed.

2023-08-02 20:51 UTC, calderpg approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/calderpg/common_robotics_utilities/70#-:-Nas0Lx819DE4ZK_4Ztj:bnfp4nl)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2023-08-02 20:52 UTC, merged

2023-08-02 21:03 UTC, jwnimmer-tri commented
What's the process for getting https://github.com/ToyotaResearchInstitute/common_robotics_utilities up to date with a merge commit?

2023-08-02 21:09 UTC, calderpg commented
In the past, I used the "Sync fork" option in the Github web interface. It used to be limited to creating merge commits, which has led to the TRI fork being kinda odd. Since Github improved the behavior of the sync option, I've now gone ahead and had it remove the old merge commits so the sync behavior will be cleaner in the future.

2023-08-02 21:22 UTC, jwnimmer-tri commented
The force-push to `TRI/CRU/master` deleted the git commit shas that Drake and Anzu had been pinning to.

I think I've been able to recover it by tagging a release as of the copy a couple of weeks ago, which _should_ preserve the history of all of the other merge commits in the ancestry of that re.ease

https://github.com/ToyotaResearchInstitute/common_robotics_utilities/releases/tag/v0.0.20230713

2023-08-02 21:28 UTC, calderpg commented
Thanks for adding the tag. I realized just after I clicked that option that it probably was more destructive than it appeared to be.